application: odata
version: 1
runtime: python
api_version: 1

handlers:
- url: /odata.svc(/.*)
  script: odata-gae.py

- url: /clientaccesspolicy.xml
  script: clientaccesspolicy.py

- url: /static
  static_dir: static

