application: odata
version: 1
runtime: python
api_version: 1

handlers:
- url: /odata.svc(/.*)
  script: odata-gae.py

- url: /static
  static_dir: static

- url: /clientaccesspolicy.xml
  static_files: clientaccesspolicy.xml
  upload: clientaccesspolicy.xml
