application: odata
version: 1
runtime: python
api_version: 1

handlers:
- url: /odata.svc(/.*)
  script: odata-gae.py
- url: /echo500(/.*)
  script: odata-gae.py

- url: /static
  static_dir: static

- url: /
  script: main.py

